version: '3.2'

services:
  ansible:
    image: ansible:1.0
    build: .
    container_name: ansible
    volumes:   # Comment out the volume section if you want to work on the code in live mode
      - type: bind
        source: ./playbooks 
        target: /ansible
      - type: bind
        source: ./roles 
        target: /etc/ansible/roles
    stdin_open: true
    tty: true 